uvicorn:
  host: "0.0.0.0"
  port: 8080
  # reload: true
  log_config: src/client/resources/log.ini

fastapi:
  title: Python Test Client
  version: 0.0.1
  contact:
    name: djccnt15
    url: https://djccnt15.github.io/
    email: djccnt15@gmail.com
  license_info:
    name: MIT
    url: https://en.wikipedia.org/wiki/MIT_License
  description: Python Client Role Test Server
  openapi_tags:
    - name: default
      externalDocs:
        description: External docs
        url: https://djccnt15.github.io/
    - name: server
      description: Request to main server
      externalDocs:
        description: External docs
        url: http://127.0.0.1:8000
    - name: redis
      description: Request to Redis
      externalDocs:
        description: External docs
        url: https://redis.io/
    - name: chat
      description: Pub/Sub design pattern chat with Redis
      externalDocs:
        description: External docs
        url: https://redis.io/
    - name: rabbitmq
      description: Request to RabbitMQ
      externalDocs:
        description: External docs
        url: https://www.rabbitmq.com/

server:
  host: http://127.0.0.1
  port: 8000

redis:
  host: 127.0.0.1
  port: 6379
  decode_responses: true
  db: 0